#include "clock_protocol.h"

#include "esp_log.h"
#include "esp_err.h"

#include "clock_alarm.h"
#include "clock_menu.h"

static const char *TAG = "CLOCK_PROTOCOL";

static clock_protocol_context_t s_ctx = {};

void clock_protocol_init(const clock_protocol_context_t *ctx)
{
    if (ctx != NULL) {
        s_ctx = *ctx;
    }
}


static uint8_t bcd_to_dec(uint8_t bcd)
{
    return ((bcd >> 4) * 10) + (bcd & 0x0F);
}

static bool bcd_is_valid(uint8_t bcd)
{
    return ((bcd & 0x0F) <= 9) && (((bcd >> 4) & 0x0F) <= 9);
}



static int ethernet_intensity_to_level(uint8_t intensity)
{
    /*
     * Ethernet software sends intensity 0-255.
     * Local clock menu uses brightness level 1-10.
     */

    if (intensity < 1) {
        intensity = 1;
    }

    int level = ((int)intensity * 10 + 254) / 255;

    if (level < 1) {
        level = 1;
    }

    if (level > 10) {
        level = 10;
    }

    return level;
}

static uint8_t brightness_level_to_protocol_intensity(int level)
{
    if (level < 1) {
        level = 1;
    }

    if (level > 10) {
        level = 10;
    }

    return (uint8_t)((level * 255) / 10);
}

bool rtc_time_is_valid(const ds3231_time_t *time)
{
    if (!time) {
        return false;
    }

    if (time->year < 2025 || time->year > 2099) {
        return false;
    }

    if (time->month < 1 || time->month > 12) {
        return false;
    }

    int max_day = clock_menu_days_in_month(time->month, time->year);

    if (time->day < 1 || time->day > max_day) {
        return false;
    }

    if (time->hour > 23) {
        return false;
    }

    if (time->minute > 59) {
        return false;
    }

    if (time->second > 59) {
        return false;
    }

    if (time->day_of_week < 1 || time->day_of_week > 7) {
        return false;
    }

    return true;
}


int clock_protocol_rx_callback(const uint8_t *p,
                               int len,
                               uint8_t *tx,
                               int tx_max)
{
	ESP_LOGI(TAG, "Command from Ethernet received: %d bytes", len);

	    /*
	     * Ignore keep-alive / poll.
	     */
	    if (len == 3 &&
	        p[0] == 0x00 &&
	        p[1] == 0x00 &&
	        p[2] == 0x00) {
	        ESP_LOGI(TAG, "Ethernet keep-alive / poll received");
	        return -1;
	    }

	    /*
	     * CT command:
	     * /TA <ID> CT <Formato2412> <Intensidad_Luminosa> \
	     *
		 * Formato2412 observed from Zeit software:
		 * 0 = 12H
		 * 1 = 24H
		 *
		 * Note:
		 * This is opposite to what the document appears to say,
		 * but this mapping matches the actual PC software behavior.
	     *
	     * Intensidad_Luminosa:
	     * 0-255 from software.
	     */
	    if (len == 9 &&
	        p[0] == '/' &&
	        p[1] == 'T' &&
	        p[2] == 'A' &&
	        p[4] == 'C' &&
	        p[5] == 'T' &&
	        p[8] == '\\') {

	        uint8_t board_id = p[3];
	        uint8_t format_2412 = p[6];
	        uint8_t intensity = p[7];

	        ESP_LOGI(TAG,
	                 "CT command: id=%u format=%u intensity=%u",
	                 board_id,
	                 format_2412,
	                 intensity);

	        /*
	         * Accept only board ID 0 for now.
	         */
	        if (board_id != 0x00) {
	            ESP_LOGW(TAG, "Ignoring CT command for different board ID: %u", board_id);
	            return -1;
	        }

			if (format_2412 > 1) {
			    ESP_LOGW(TAG, "Invalid CT format value: %u", format_2412);
			    return -1;
			}

			hour_format_t new_format =
			    (format_2412 == 0) ? FORMAT_12H : FORMAT_24H;

	        int new_brightness_level =
	            ethernet_intensity_to_level(intensity);

	        ESP_LOGI(TAG,
	                 "Ethernet intensity %u converted to brightness level %d",
	                 intensity,
	                 new_brightness_level);

			 portENTER_CRITICAL(s_ctx.data_mux);

			 *s_ctx.eth_brightness_level = new_brightness_level;
			 *s_ctx.eth_brightness_pending = true;

			 *s_ctx.eth_format = new_format;
			 *s_ctx.eth_format_pending = true;

			 portEXIT_CRITICAL(s_ctx.data_mux);

	        return 0;
	    }
		
		/*
		 * ES command:
		 * /TA <ID> ES \
		 *
		 * Estado del Sistema / Is Online.
		 * ACK is generated by clock_ethernet.cpp:
		 * /ta <ID> es \
		 */
		 if (len == 7 &&
		     p[0] == '/' &&
		     p[1] == 'T' &&
		     p[2] == 'A' &&
		     p[4] == 'E' &&
		     p[5] == 'S' &&
		     p[6] == '\\') {

		     uint8_t board_id = p[3];

		     ESP_LOGI(TAG, "ES online/status command received: id=%u", board_id);

		     if (board_id != 0x00) {
		         ESP_LOGW(TAG, "Ignoring ES command for different board ID: %u", board_id);
		         return -1;
		     }

			 clock_alarm_arm_full_replacement();

		     return 0;
		 }
		
		/*
		 * UC command:
		 * /TA <ID> UC <ss><mm><hh><DoW><dd><MM><yy> \
		 *
		 * Time bytes are BCD according to the protocol.
		 */
		if (len == 14 &&
		    p[0] == '/' &&
		    p[1] == 'T' &&
		    p[2] == 'A' &&
		    p[4] == 'U' &&
		    p[5] == 'C' &&
		    p[13] == '\\') {

		    uint8_t board_id = p[3];

		    if (board_id != 0x00) {
		        ESP_LOGW(TAG, "Ignoring UC command for different board ID: %u", board_id);
		        return -1;
		    }

		    for (int i = 6; i <= 12; i++) {
		        if (!bcd_is_valid(p[i])) {
		            ESP_LOGW(TAG, "Invalid BCD byte in UC at index %d: 0x%02X", i, p[i]);
		            return -1;
		        }
		    }

		    ds3231_time_t new_time = {};

			new_time.second = bcd_to_dec(p[6]);
			new_time.minute = bcd_to_dec(p[7]);
			new_time.hour   = bcd_to_dec(p[8]);

			uint8_t received_dow = bcd_to_dec(p[9]);

			new_time.day   = bcd_to_dec(p[10]);
			new_time.month = bcd_to_dec(p[11]);
			new_time.year  = 2000 + bcd_to_dec(p[12]);

			/*
			 * Do not trust Ethernet DoW because the PC software may use
			 * a different convention:
			 *
			 * 0 = Sunday, 1 = Monday
			 * or
			 * 1 = Sunday, 2 = Monday
			 *
			 * Our clock already has a known-good weekday calculator.
			 */
			new_time.day_of_week = clock_menu_calculate_weekday(
			    new_time.day,
			    new_time.month,
			    new_time.year
			);

			ESP_LOGI(TAG,
			         "UC received DoW=%u, calculated DoW=%d",
			         received_dow,
			         new_time.day_of_week);

		    if (!rtc_time_is_valid(&new_time)) {
		        ESP_LOGW(TAG,
		                 "Invalid UC time: %04d-%02d-%02d %02d:%02d:%02d DOW=%d",
		                 new_time.year,
		                 new_time.month,
		                 new_time.day,
		                 new_time.hour,
		                 new_time.minute,
		                 new_time.second,
		                 new_time.day_of_week);
		        return -1;
		    }

			portENTER_CRITICAL(s_ctx.data_mux);

			*s_ctx.eth_time = new_time;
			*s_ctx.eth_time_pending = true;

			portEXIT_CRITICAL(s_ctx.data_mux);

		    ESP_LOGI(TAG,
		             "UC time received: %04d-%02d-%02d %02d:%02d:%02d DOW=%d",
		             new_time.year,
		             new_time.month,
		             new_time.day,
		             new_time.hour,
		             new_time.minute,
		             new_time.second,
		             new_time.day_of_week);

		    return 0;
		}
		
		/*
		 * RC command:
		 * /TA <ID> RC \
		 *
		 * Response:
		 * /ta <ID> rc <IMW><Formato2412><Intensidad><ss><mm><hh><DoW><dd><MM><yy> \
		 */
		if (len == 7 &&
		    p[0] == '/' &&
		    p[1] == 'T' &&
		    p[2] == 'A' &&
		    p[4] == 'R' &&
		    p[5] == 'C' &&
		    p[6] == '\\') {

		    uint8_t board_id = p[3];

		    ESP_LOGI(TAG, "RC read config command received: id=%u", board_id);

		    if (board_id != 0x00) {
		        ESP_LOGW(TAG, "Ignoring RC command for different board ID: %u", board_id);
		        return -1;
		    }

		    if (tx == NULL || tx_max < 17) {
		        ESP_LOGE(TAG, "TX buffer too small for RC response");
		        return -1;
		    }

		    ds3231_time_t now_copy;
		    hour_format_t format_copy;
		    int brightness_level_copy;
		    bool rtc_valid_copy;

			portENTER_CRITICAL(s_ctx.data_mux);

			now_copy = *s_ctx.now;
			format_copy = *s_ctx.clock_format;
			brightness_level_copy = *s_ctx.brightness_level;
			rtc_valid_copy = *s_ctx.rtc_valid;

			portEXIT_CRITICAL(s_ctx.data_mux);

		    if (!rtc_valid_copy) {
		        ESP_LOGW(TAG, "RC requested but RTC is not valid");
		        return -1;
		    }

		    uint8_t format_2412 = (format_copy == FORMAT_12H) ? 0 : 1;
		    uint8_t intensity = brightness_level_to_protocol_intensity(brightness_level_copy);

		    /*
		     * RC document says time fields are HEX, not BCD.
		     */
		    tx[0]  = '/';
		    tx[1]  = 't';
		    tx[2]  = 'a';
		    tx[3]  = board_id;
		    tx[4]  = 'r';
		    tx[5]  = 'c';

		    tx[6]  = 0x01; // IMW: IsMemoryWritten. Use 1 = valid/configured.
		    tx[7]  = format_2412;
		    tx[8]  = intensity;

		    tx[9]  = (uint8_t)now_copy.second;
		    tx[10] = (uint8_t)now_copy.minute;
		    tx[11] = (uint8_t)now_copy.hour;

		    /*
		     * Use your internal day_of_week value.
		     * If software shows wrong weekday later, we can map it here.
		     */
		    tx[12] = (uint8_t)now_copy.day_of_week;

		    tx[13] = (uint8_t)now_copy.day;
		    tx[14] = (uint8_t)now_copy.month;
		    tx[15] = (uint8_t)(now_copy.year % 100);

		    tx[16] = '\\';

		    ESP_LOGI(TAG,
		             "RC response: format=%u intensity=%u time=%04d-%02d-%02d %02d:%02d:%02d DOW=%d",
		             format_2412,
		             intensity,
		             now_copy.year,
		             now_copy.month,
		             now_copy.day,
		             now_copy.hour,
		             now_copy.minute,
		             now_copy.second,
		             now_copy.day_of_week);

		    return 17;
		}
		
		/*
		 * CA command:
		 * /TA <ID> CA <Alarma_ID><Hora_Alarma[2]><Frecuencia><Duracion&Efecto> \
		 *
		 * ACK:
		 * /ta <ID> ca <Alarma_ID> \
		 */
		if (len == 12 &&
		    p[0] == '/' &&
		    p[1] == 'T' &&
		    p[2] == 'A' &&
		    p[4] == 'C' &&
		    p[5] == 'A' &&
		    p[11] == '\\') {

		    uint8_t board_id = p[3];

		    if (board_id != 0x00) {
		        ESP_LOGW(TAG, "Ignoring CA command for different board ID: %u", board_id);
		        return -1;
		    }

		    uint8_t alarm_id = p[6];
		    uint8_t alarm_hh = p[7];
		    uint8_t alarm_mm = p[8];
		    uint8_t frequency = p[9];
		    uint8_t duration_effect = p[10];

		    if (alarm_id < 1 || alarm_id > MAX_ETH_ALARMS) {
		        ESP_LOGW(TAG, "Invalid CA alarm_id=%u", alarm_id);
		        return -1;
		    }

		    if (alarm_hh > 23 || alarm_mm > 59) {
		        ESP_LOGW(TAG, "Invalid CA alarm time: %02u:%02u", alarm_hh, alarm_mm);
		        return -1;
		    }

			esp_err_t alarm_ret = clock_alarm_store_from_ca(alarm_id,
			                                                alarm_hh,
			                                                alarm_mm,
			                                                frequency,
			                                                duration_effect);

			if (alarm_ret != ESP_OK) {
			    return -1;
			}


		    tx[0] = '/';
		    tx[1] = 't';
		    tx[2] = 'a';
		    tx[3] = board_id;
		    tx[4] = 'c';
		    tx[5] = 'a';
		    tx[6] = alarm_id;
		    tx[7] = '\\';

		    return 8;
		}
		
		/*
		 * LA command:
		 * /TA <ID> LA <Alarma_ID> \
		 *
		 * ACK:
		 * /ta <ID> la <Alarma_ID><HH><MM><Frecuencia><Duracion&Efecto> \
		 */
		if (len == 8 &&
		    p[0] == '/' &&
		    p[1] == 'T' &&
		    p[2] == 'A' &&
		    p[4] == 'L' &&
		    p[5] == 'A' &&
		    p[7] == '\\') {

		    uint8_t board_id = p[3];

		    if (board_id != 0x00) {
		        ESP_LOGW(TAG, "Ignoring LA command for different board ID: %u", board_id);
		        return -1;
		    }

		    uint8_t alarm_id = p[6];

		    if (alarm_id < 1 || alarm_id > MAX_ETH_ALARMS) {
		        ESP_LOGW(TAG, "Invalid LA alarm_id=%u", alarm_id);
		        return -1;
		    }

			ethernet_alarm_t alarm_copy;

			if (!clock_alarm_read(alarm_id, &alarm_copy)) {
			    ESP_LOGW(TAG, "Invalid LA alarm_id=%u", alarm_id);
			    return -1;
			}

		    ESP_LOGI(TAG,
		             "LA read alarm: id=%u configured=%d time=%02u:%02u freq=0x%02X dur_eff=0x%02X",
		             alarm_id,
		             alarm_copy.configured,
		             alarm_copy.time_hh,
		             alarm_copy.time_mm,
		             alarm_copy.frequency,
		             alarm_copy.duration_effect);

		    if (tx == NULL || tx_max < 12) {
		        return -1;
		    }

		    tx[0] = '/';
		    tx[1] = 't';
		    tx[2] = 'a';
		    tx[3] = board_id;
		    tx[4] = 'l';
		    tx[5] = 'a';

		    tx[6]  = alarm_id;
		    tx[7]  = alarm_copy.time_hh;
		    tx[8]  = alarm_copy.time_mm;
		    tx[9]  = alarm_copy.frequency;
		    tx[10] = alarm_copy.duration_effect;

		    tx[11] = '\\';

		    return 12;
		}
		
		
		
		/*
		 * RT command:
		 * /TA <ID> RT <Reset_ID> \
		 *
		 * reset_id = 0x00 -> reset device settings/defaults
		 *
		 * ACK:
		 * /ta <ID> rt \
		 */
		if (len == 8 &&
		    p[0] == '/' &&
		    p[1] == 'T' &&
		    p[2] == 'A' &&
		    p[4] == 'R' &&
		    p[5] == 'T' &&
		    p[7] == '\\') {

		    uint8_t board_id = p[3];
		    uint8_t reset_id = p[6];

		    ESP_LOGI(TAG,
		             "RT reset command received: board_id=%u reset_id=0x%02X",
		             board_id,
		             reset_id);

		    if (board_id != 0x00) {
		        ESP_LOGW(TAG, "Ignoring RT command for different board ID: %u", board_id);
		        return -1;
		    }

		    if (reset_id != 0x00) {
		        ESP_LOGW(TAG, "Unknown RT reset_id=0x%02X", reset_id);
		        return -1;
		    }

			portENTER_CRITICAL(s_ctx.data_mux);
			*s_ctx.factory_reset_pending = true;
			portEXIT_CRITICAL(s_ctx.data_mux);

		    ESP_LOGW(TAG, "RT Reset All received, factory reset pending");

		    /*
		     * Generic ACK will be sent:
		     * /ta <ID> rt \
		     */
		    return 0;
		}
		

		ESP_LOGW(TAG, "Unknown Ethernet command");
		return -1;
}








